# №11 Переменные в GitHub Actions
#
# Переменные служебные: 
# https://docs.github.com/en/actions/learn-github-actions/variables#default-environment-variables
# Служебные: $GITHUB_REF; $GITHUB_SHA; ...
# Персональные: бывают уровня (всего) 'workflow' и уровня 'jobs' и уровня 'steps'
# env: служебное слово, начала объявления перемнных.

name: Eleventh Workflow
on: [push]
env:
  # доступна во всём файле, во всех шагах:
  WF_CUSTOM_VAR: WF 1
jobs:
  run-first-command:
    runs-on: ubuntu-latest
    env:
      JOB_CUSTOM_VAR: JOB 1
    steps:
      - name: Set New Var
        run: echo "NEW_CUSTOM_VAR=New Value" >> "$GITHUB_ENV"
      - name: Vars
        env:
          STEP_CUSTOM_VAR: STEP 1
          # переопредилили знач.:
          WF_CUSTOM_VAR: WF 1 - STEP 2
        run: |
          echo $GITHUB_REF
          echo '${{ github.ref }}'
          echo $WF_CUSTOM_VAR             # способ 1.
          echo '${{ env.WF_CUSTOM_VAR }}' # способ 2.
          echo $JOB_CUSTOM_VAR
          echo $STEP_CUSTOM_VAR
          echo $NEW_CUSTOM_VAR