# №15 Артифакты похож на "Кэш". Отличие:
#
# - "Артифакты" хранится на GitHub Actions - до 90 дней (или менее, указ-ся). 
# 
# Первый 'job' - делает вычисление формирует файл.
# Второй 'job' - считывает, записывает новое значение, созраняет (загружает) файл.
# Третий 'job' - получает считывает выводит на экран.
#

name: Fifteenth Workflow
on: push
jobs:

  # Формирует 'Артефакт' файл с результатом на сервере 'GitHub Actions'.
  first-jobs:                                 # Первый 'job' создаст и загрузит артифакт
    runs-on: ubuntu-latest
    steps:
      - name: Math expression
        run: expr 2 + 2 > math-result.txt     # математическая команда результат с выводом в файл.
      - name: Upload result file
        uses: actions/upload-artifact@v4      # плагин загрузки на сервер 'GitHub Actions', 'Артифакта'.
        with:
          name: math-result                   # соответствует КЛЮЧУ (по ниму будим обращаться).
          path: math-result.txt               # путь к файлу. Какой файл добавлять в 'Артифакты'.
  
  # Изменим значение в файле -'Артефакт', и загрузим потовому на сервер 'GitHub Actions'
  another-job:
    runs-on: ubuntu-latest
    needs: first-jobs                         # запускать последовательно, после 'first-jobs'
    steps:
      - name: Download file
        uses: actions/download-artifact@v4     # Скачиваем файл
        with:
          name: math-result
      - name: Math Expression
        run: |
          value=`cat math-result.txt`           # Считываем значение из файла
          expr $value \* 2 > math-result.txt    # Умнажаем на 2 и записываем в файл
      - name: Upload result file
        uses: actions/upload-artifact@v4        # Загружаем на сервер
        with:
          name: math-result
          path: math-result.txt

  # Считывает -'Артефакт' созданный файл c 'GitHub Actions', с результатом в консоль.
  second-job:
    runs-on: ubuntu-latest
    needs: another-job                     # запускать последовательно, после 'another-job'
    #needs: first-jobs                       # запускать последовательно, после 'first-jobs'
    steps:
      - name: Download file
        uses: actions/download-artifact@v4  # плагин загрузки из файла с 'GitHub Actions'
        with:
          name: math-result
      - name: Print File
        run: |
          value=`cat math-result.txt`        # получить значение файла
          echo $value                        # отобразить на экран