# № 17
#
#      

###########################################
# v1 Вызывает/запускает -  'workflow.yml' 
name: Seventeenth Workflow
on: 
  workflow_dispatch:                        # Запуск в ручную
    inputs:
      title:
        description: "_Custom Title_"
        type: string
        default: "Testing text title"
        required: false
jobs: 
  call-workflow:                            # вызов 'workflow.yml' 
    uses: ./.github/workflows/workflow.yml
    with:
      title: ${{ inputs.title }}
      




###########################################
# v2 
# name: Seventeenth Workflow
# on: 
#   workflow_dispatch:
#     inputs:
#       title:
#         description: "Custom Title"
#         type: string
#         default: "Testing text title"
#         required: false
# jobs:
#   call-workflow:
#     uses: ./.github/workflows/workflow.yml
#     with:
#       title: ${{ inputs.title }}
#   call-external-workflow:
#     uses: CRIK0VA/workflows/.github/workflows/workflow.yml@main
#     secrets:
#       PASSWORD: ${{ secrets.PASSWORD }}
#   display-output:
#     runs-on: ubuntu-latest
#     needs: call-workflow
#     steps:
#       - run: echo ${{ needs.call-workflow.outputs.date }}