# №7 Запуск 'Workflow' по расписанию. Каждые 5 минут. (Меньше нельзя).
# - cron: "*/5 * * * *"
# После 'попадания на сервер запустится через определённое время, 
# и продолжит запускаться согласно параметрам'
# ! Github может сам отложить его исходя из нагрузки на свои сервера.

name: Seventh Workflow
on:
  schedule:
    - cron: "*/10 * * * *"

jobs:
  run-first-command:
    runs-on: ubuntu-latest
    steps:
      - name: Event Vars
        run: |
          echo $GITHUB_SHA
          echo $GITHUB_REF
