# №10 Оператор if, выражения, контексты в GitHub Actions
#
# Вывод в консоль в формате JSON, то что передаём.

name: Ten Workflow
on: [push]
run-name: "Display Context Info"
jobs:
  run-first-command:
    runs-on: ubuntu-latest
    steps:
      - name: Contexts and Expressions
        id: context-expression         # для поиска в логах
        run: |
          echo '${{ toJson(github) }}' # выражение
          echo '${{ toJson(runner) }}'
          echo '${{ toJson(job) }}'
          echo '${{ toJson(steps) }}'
      - name: Show Steps Context
        run: echo '${{ toJson(steps) }}'