# №13 Функции и GitHub Actions
#
# Документация:
# https://docs.github.com/en/actions/learn-github-actions/expressions#status-check-functions

#####################################
# ::: Для проврки по нажатию кнопки 'отмены' в 'GitHub Action' :::

# name: Thirteenth Workflow
# on: push

# jobs:
#   # failure() success() always() cancelled()
#   job:
#     runs-on: ubuntu-latest
#     steps:
#       - name: First Step
#         run: sleep 30                 # чтобы успеть нажать кнопку в 'GitHub Action'.
#       - name: Runs on Canceled
#         if: ${{ cancelled() }}        # вернёт 'true' если предидущие шаги были отменены.
#         run: echo "Runs on Canceled"
#       - name: Runs on any case
#         if: ${{ always() }}           # возвращает 'true' при любом состоянии.
#         run: echo "Runs on any case"
#       - name: Runs on Success
#         if: ${{ success() }}          # шаг удачный.
#         run: echo "Runs on Success"
#       - name: Runs on Failure
#         if: ${{ failure() }}  # шаг не удачный.
#         run: echo "Runs on Failure"

################################
# Выполнять 'second-job:' только если первый 'job:' провален.
name: Thirteenth Workflow
on: push

jobs:
  # failure() success() always() cancelled()
  job:
    runs-on: ubuntu-latest
    steps:
      - name: Failure Step
        id: error-step                # по id можно порверить завершился ли шаг(см. ниже).
        run: exit 1                   # 'ВЫХОД' - имитация прерывания прогр.
      - name: Runs on Canceled
        if: ${{ cancelled() }}        # вернёт 'true' если предидущие шаги были отменены.
        run: echo "Runs on Canceled"
      - name: Runs on any case
        if: ${{ always() }}           # возвращает 'true' при любом состоянии.
        run: echo "Runs on any case"
      - name: Runs on Success
        if: ${{ success() }}          # шаг удачный.
        run: echo "Runs on Success"
      - name: Runs on Failure
        if: ${{ failure() && steps.error-step.conclusion == 'failure' }}  # конкретный шаг не удачный.
        run: echo "Runs on Failure"
  second-job:                         # второй 'second-job:' зависит от первого 'job:'
    runs-on: ubuntu-latest
    needs: job                        # зависимость
    if: ${{ failure() }}              # выполнить если неудачен первый 'job:'
    steps:
      - run: echo "Job was failed"