# №3 РУЧНОЙ ("Git File Copy") и скриптом ("checkout")
# Копирует файлы из репозитория GitHub в Рабочий каталог VM.
# - uses: actions/checkout@v4 (скрипт https://github.com/actions/checkout)

name: Third Workflow
on: push

jobs:
  run-first-command:
    runs-on: ubuntu-latest
    steps:
      - name: List Files
        run: ls -a
      #- uses: actions/checkout@v4
      - name: Copy Files
        run: |
          git init
          git remote add origin "https://$GITHUB_ACTOR:${{secrets.GITHUB_TOKEN}}@github.com/$GITHUB_REPOSITORY.git"
          git fetch origin
          git checkout main
      - name: List Files
        run: ls -a