# Лимитируем время выполнения Workflow
#
#############################

#############################
# Ограничение на уровне исполнения всего 'job' 1 минута 
# имитация задержки выполнения
#############################
name: Test Timeout
on: push

jobs:
  test-timeout:
    runs-on: ubuntu-latest
    timeout-minutes: 1             # Ограничение на уровне исполнения всего 'job' 1 минута
    steps: 
      - name: Some Step            # имитация задержки выполнения - более минуты.
        run: sleep 200             # 200 секунд 

				
#############################
# Ограничение на уровне шага  1 минута
#############################
# name: Test Timeout
# on: push

# jobs:
#   test-timeout:
#     runs-on: ubuntu-latest
#     steps: 
#       - name: Some Step
#         run: sleep 10
#         timeout-minutes: 1             # Ограничение на уровне шага